name: swot_simulator
dependencies:
  - dask
  - distributed
  - netcdf4
  - numba
  - numpy
  - numpy
  - pyinterp>=0.3.2
  - python-dateutil
  - python>=3.6
  - scipy
  - xarray
channels:
  - conda-forge
