{% set name = "swot_simulator" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/CNES/swot_simulator
    git_rev: HEAD

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - dask
    - distributed
    - numba
    - {{ pin_compatible('numpy') }}
    - pyinterp
    - python {{ python }}
    - python-dateutil
    - scipy
    - xarray
test:
  imports:
    - swot_simulator.launcher
