name: swot_simulator
channels:
  - conda-forge

dependencies:
  - cartopy
  - dask
  - distributed
  - furo
  - gcsfs
  - git
  - intake
  - intake-xarray
  - jupyter
  - netcdf4
  - numba
  - numpy
  - pandas
  - pyinterp
  - python
  - python-dateutil
  - scipy
  - xarray
  - zarr
